version: '3.8'

services:

  recommender:
    image: recommender
    build:
      context: .
      dockerfile: Dockerfile.deploy
    container_name: recommender_container
    ports:
      - "8000:8000"
    env_file:
      - yanr/workflow/dvc/word2vec/.env
    working_dir: /opt/yanr/yanr/workflow/dvc/word2vec
    command: python -m uvicorn deploy:app --host=0.0.0.0 --port=8000