timeout: 10
interval: 600
num_workers: 7
seed: 42
remote_kwargs:
  runtime_env:
    env_vars:
      AWS_ACCESS_KEY_ID: ~
      AWS_SECRET_ACCESS_KEY: ~
worker: Parser
worker_kwargs:
  bucket: yanr
  prefix: news
  service_name: s3
  storage_class: STANDARD
  region: ru-central1
  endpoint_url: https://storage.yandexcloud.net
  max_cache_size: 100000
feeds:
  - https://cointelegraph.com/rss
  - https://www.newsbtc.com/feed
  - https://www.cryptoninjas.net/feed/
  - https://news.bitcoin.com/feed/
  - https://blog.coinbase.com/feed
  - https://www.financemagnates.com/cryptocurrency/feed/
  - https://blog.kraken.com/feed
  - https://themarketscompass.substack.com/feed
  - https://www.bitcoin-rss.com/
  - https://medium.com/feed/buyucoin-talks
  - https://medium.com/feed/@nikita-monastyrskiy
  - https://blog.wazirx.com/feed/
  # - https://blog.paxful.com/feed
  - https://coinstats.app/blog/feed/
  - https://blog-eu.bitflyer.com/rss/
  - https://cryptopotato.com/feed
  - https://www.bitdegree.org/crypto/news/rss
  - https://cryptobriefing.com/feed/
  - https://cryptoslate.com/feed/
  - https://u.today/rss
  - https://bitcoinist.com/feed/
  - https://www.buyucoin.com/crypto-labs/feed
  - https://bitcoinmagazine.com/feed
  - https://coinpedia.org/feed/
  - https://zebpay.com/feed/
  - https://www.cryptonewsz.com/feed/
  - https://blog.liquid.com/rss.xml
  - https://blog.aragon.org/feed
  - https://zycrypto.com/feed/
  - https://99bitcoins.com/feed/
  - https://nowpayments.io/blog/feed
  - https://coinquora.com/news/feed/
  - https://www.coinspeaker.com/feed/
  - https://blogs.airdropalert.com/feed/
  - https://www.crypto-news-flash.com/feed/
  # - https://bytes.localcryptos.com/
  - https://insidebitcoins.com/feed
  - https://simpleswap.io/blog/feed
  - https://coinsutra.com/blog/feed/
  - https://coincheckup.com/blog/feed/
  - https://feeds.feedburner.com/neironix-en
  - https://coinjournal.net/feed/
  - https://blog.nomics.com/feed/
  - https://blockonomi.com/feed/
  - https://bitcoinik.com/feed/
  - https://coincentral.com/news/feed/
  - https://bravenewcoin.com/news/rss
  - https://cryptoticker.io/en/feed/
  - https://blockchain.news/rss
  - https://thecryptobasic.com/feed/
  - https://dailycoin.com/feed/
  - https://thenewscrypto.com/feed/
  - https://coinratecap.com/rss-feed
  - https://www.coolwallet.io/news/feed/
  - https://coindoo.com/feed/
  - https://cryptosrus.com/feed
  - https://blog.localcoinswap.com/rss/
  - https://cryptogeek.info/en/blog
  - https://stealthex.io/blog/feed/
  - https://komodoplatform.com/en/blog/rss/
  - https://ciphertrace.com/feed/
  - https://cryptoadventure.com/feed/
  - https://cryptoverze.com/feed/
  - https://coinfunda.com/feed/
  - https://www.cryptomaton.org/feed/
  - https://coinjoy.io/
  - https://www.tronweekly.com/feed/
  - https://nulltx.com/feed/
  - https://www.cryptoground.com/feeds.xml?format=xml
  - https://thetradingbay.com/feed/
  - https://crypto-academy.org/feed/
  - https://cryptonews.com.au/feed/
  - https://www.bitrates.com/feed/rss
  - https://cryptocurrencyfacts.com/blog/feed/
  - https://ethereumworldnews.com/feed
  - https://blog.digitex.io/feed/
  - https://www.bitcoinmarketjournal.com/feed/
  - https://crypto-economy.com/feed/
  - https://e-cryptonews.com/feed/
  - https://bitpinas.com/feed/
  - https://fullycrypto.com/feed
  - https://rss2.feedspot.com/https://digicryptopedia.com/?context=2151547387
  - https://cryptostaunch.com/feed
  - https://www.platinumcryptoacademy.com/feed/
  - https://www.cryptocointrade.com/feed/
  - https://ox-currencies.com/feed/
  - https://coinwink.com/blog/feed
  - https://coinrevolution.com/feed/
  - https://coinchapter.com/feed
  - https://www.dcforecasts.com/feed/
  - https://bitrss.com/rss.xml
  - https://skyytracker.com/blog/feed/
  - https://www.crypto-news.net/feed/
  - https://www.cryptocurrencyguide.org/feed/
  - https://alexablockchain.com/feed/
  - https://www.bitprime.co.nz/feed/
  - https://cryptoexchange4u.com/feed/
  - https://coinscribble.com/feed/
  - https://cryptobreaking.com/feed/
  - https://blog.coinfabrik.com/feed
  - https://cryptowhat.com/feed/
  - https://lewlewcrypto.com/feed/
  - https://www.bitcointe.com/feed
  - https://cryptocoinspy.com/feed/
  - https://cryptospacey.com/feed/
  - https://coinful.net/feed/
  - https://mindlesscryptonews.com/feed/
  - https://vestorportal.com/rss/
  - https://www.coin-tradeandmine.com/feed/
  - http://cryptopost.com/feed/
  - https://thecryptogarage.com/feed/
  - https://www.newscryptotoday.de/feeds/posts/default
  - https://diamcircle.io/feed/
  - https://techyno.com/feed/
  - https://mcc.exchange/feed/
  - http://ccxnews.com/feed/
  - https://coinregwatch.com/feed/
  - https://www.coin24h.com/feed/
  - https://cryptonews.exchange/feed/
  - https://www.btcethereum.com/blog/feed/
  - https://www.coinkurry.com/feed/
  - https://www.kanalcoin.com/feed/
  - https://rss2.feedspot.com/https://coinprologue.com/?context=3839478750
  - https://usethebitcoin.com/feed
  - https://blufol.io/feed/
  - https://visionary-finance.com/feed/gn
  - https://www.globalcryptopress.com/feeds/posts/default?alt=rss
  - https://www.fxopen.blog/feed/
  - https://rss2.feedspot.com/https://www.etorexchange.in/blog?context=1783085415
  - https://www.helenabitcoinmining.com/feed/
  - https://bitcoinchaser.com/feed/
  - https://cryptobullsclub.com/feed/
  - https://blog.cakedefi.com/rss/
  - https://cryptocorral.com/~api/papers/3b72a8ab-c509-4ee8-ac07-51abbc142a0e/rss
  - https://coincolumnist.com/feed/
  - https://www.cryptopressdaily.com/feed/
  - https://cryptoinfos.eu/feed/
  - https://coingape.com/feed/
  - https://www.thecoinspost.com/feed/
  - http://www.talkcrypto.org/blog/feed/
  - https://coinotizia.com/feed/
  - https://cryptoandblockchaintalk.com/rss
  - https://coinmetro.com/blog/feed/
  - https://www.monetran.com/feed/
  - https://bitcoinethereumnews.com/feed
  - https://cryptocurrencymarket.us/feed/
  - https://freebtctap.wordpress.com/feed/
  - https://cryptomarketoptimists.com/feed/
  - https://cryptodefix.com/rss?type=&tag=
  - https://cointikka.com/feed/
  - https://cryptopriceticker.com/rss
  - https://cryptoenabler.com/feed/
  - https://ledgernomic.com/feed/
  - https://plezna.com/rss/
  - https://cryptogiggle.com/feed/
  - https://tradevilley.co/feed/
  - https://cryptoonnews.xyz/feed
  - https://unft.news/feed/
  - https://www.thedailyencrypt.com/feed/
  - https://crypto-guide.info/feed/
  - https://www.datahauling.com/feeds/posts/default
  - https://www.mcrypto.in/feeds/posts/default
  - http://cryptomining-blog.com/feed/
  - https://wunderbit.co/en/rss
  - https://rss2.feedspot.com/https%3A%2F%2Fwww.coindesk.com%2F?context=2632736060
  - https://minergate.com/blog/feed/
  - https://rss2.feedspot.com/https://www.bitdegree.org/tutorials/?context=31189579
  - https://changelly.com/blog/feed/
  - https://rss2.feedspot.com/https://www.koinbazar.com/blog
  - https://bitcoinexchangeguide.com/feed/
  - https://cryptoandfire.com/feed/
  - https://www.cryptocoinsociety.com/feed/
  - https://blog.coinspectator.com/feed/
  - https://cryptopurview.com/feed/
  - https://fortunez.com/feed/
  - https://sweatcoinguide.com/feed/
  - https://bitemycoin.com/feed/
  - https://cryptooa.com/blog/feed/
  - https://www.thedigitalpioneer.com/feed/
  - https://whaletank.trade/blog/feed/
  - https://www.blocdesk.com/feed/
  - https://cryptocanucks.com/feed
  - https://rss2.feedspot.com/https://www.coindaily.co/?context=3669452897
  - https://blog.spectrocoin.com/en/category/cryptocurrencies/feed/
  - https://www.cryptogandalf.com/blog-feed.xml
  - https://urban-crypto.com/feed/
  - https://cryptonewsia.com/feed/
  - https://cryptocomes.com/rss_feed
  - https://libranews.com/feed/
  - https://gocryptowise.com/blog/feed/
  - https://blog.infiniteblocktech.com/feed/
  - https://cryptosyringe.com/feed
  - http://www.thecryptoquartet.com/feed/
  - https://sludgefeed.com/category/cryptocurrency/feed/
  - https://api.blocktv.com/api/feed/news.rss
  - https://rehmann.co/blog/category/cryptocurrency/feed/
  - https://blockfinest.com/feed/
  - https://cryptocoinssupermarket.com/feed
  - https://www.1daydude.com/feed/
  - https://devcoins.org/
  - https://cryptohero8.com/feed/
  - http://icosource.io/blog/feed
  - https://theycallitcrypto.com/feed/
  - https://coinpress.io/feed/
  - https://crypto101.com/feed/
  - https://cryptocurrencyblog.co.za/crypto-news?format=feed&type=rss
  - https://ashleyknowles.net/feed/
  - https://dictoms.com/feed/
  - http://coinnoob.com/feed
  - https://forklog.media/feed/
  - https://futurenetafrica.blogspot.com/feeds/posts/default?alt=rss
  - https://coinmarketstrategist.com/feed
  - https://freecryptoinfo.blogspot.com/feeds/posts/default?alt=rss
  - http://www.cryptonoob.co.uk/blog/feed
  - https://coincolony.net/feed/
  - https://www.cryptopreneur.uk/feed/
  - http://coinpupil.com/feed
  - https://cryptomarketreport.org/feed
  - https://nevafomo.com/feed/
  - https://cryptozmedia.com/feed
  - https://www.cryptosteem.com/feed/
  - https://bizzcoinhub.com/feed
  - https://cryptotv.com.ng/feed
  - https://www.cryptoallcoins.com/feed/
  - https://buxcoindigicrypto.blogspot.com/feeds/posts/default
  - https://www.cryptocoinschecker.com/feeds/posts/default
  - https://crypto-tokens.net/feed/
  - http://cryptoworldseo.com/feed/
  - http://tpbit.blogspot.com/feeds/posts/default?alt=rss
  - https://thecoinalist.com/news/feed/
  - https://traderworm.com/feed/
  - https://moonwhale.io/feed/
  - https://datalight.me/blog/feed/
  - https://blog.vhcex.com/feed/
  - https://cryptonewsmonitor.com/feed/
  - https://miningcrypto.tech/feed/
  - https://rss2.feedspot.com/https://thecoinfin.com/?context=2984284878
  - https://newsblockchain.io/feed.xml
  - https://www.blockchain24.co/feed/
  - https://rss2.feedspot.com/https://p2pmoon.com/blog/?context=1947453180
  - https://www.dinardirham.com/feed/
  - https://unhashed.com/feed/
  - https://www.currencytimes.co.in/feed/
  - https://www.cryptocoinzone.com/cryptocurrency-blog/feed/
  - https://changenow.io/blog/feed
  - https://zeecourse.com/feed/
  - https://cryptocurrency-blog.com/feed/
  - https://coinmatics.com/blog/feed/
  - https://blockvila.com/blog/feed/
  - https://www.cryptodaily.co.uk/https:/www.cryptodaily.co.uk/feed
  - https://rss2.feedspot.com/https://zerocrypted.com/
  - https://www.saturn.network/blog/rss
  - https://gameofsatoshi.blogspot.com/feeds/posts/default?alt=rss
  - https://ao-x.com/feed/
  - https://www.currencycrypt.net/feed/
  - https://tsakf.org/feed/rss
  - https://cryptostart.info/feed/
  - https://www.ukbitcoinblog.com/category/bitcoin-mining/feed/
  - https://bitcoguides.com/feed
  - https://blockduo.com/feed/
  - https://www.freebtctap.com/2/feed
  - https://c3gold.com/blog/feed/
  - https://blog.latoken.com/feed
  - https://www.thecryptoassociate.com/feed/
  - https://coindiligent.com/feed
  - https://cryptoindetail.com/feed
  - https://news.daex.com/feed/
  - https://news.coinsquare.com/feed/
  - https://cryptovest.com/feed/
  - https://masterthecrypto.com/feed
  - https://www.cryptozink.io/feed/
  - https://cryptocurrencynews.com/feed/
  - https://walletinvestor.com/blog/feed/
  - https://www.cryptocurrencyfreak.com/feed/
  - https://bitrazzi.com/feed/
  - http://mycriptocurrency.blogspot.com/feeds/posts/default?alt=rss
  - http://cryptocoindude.com/feed/
  - https://icoinblog.com/feed/
  - https://cryptotradingreview.com/feed/
  - http://cryptoinvestorpro.com/feed