stages:
  preprocess:
    vars:
      - params_preprocess.yaml
    cmd: python preprocess.py params_preprocess.yaml
    params:
      - params_preprocess.yaml:
    deps:
      - ${raw_path}
      - ${coins_path}
    outs:
      - ${processed_path}
      - ${map_path}
    metrics:
      - ${report_path}:
          cache: true
    plots:
      - ${words_path}:
          cache: true
      - ${sentences_lengths_path}:
          cache: true
      - ${words_lengths_path}:
          cache: true

  train:
    vars:
      - params_train.yaml
    cmd: python train.py params_train.yaml
    params:
      - params_train.yaml:
    deps:
      - ${processed_path}
    outs:
      - ${output_path}
    metrics:
      - ${metrics_path}:
          cache: true
    plots:
      - ${plots_path}:
          cache: true

  test:
    vars:
      - params_test.yaml
    cmd: python test.py params_test.yaml
    params:
      - params_test.yaml:
    deps:
      - ${raw_path}
      - ${model_path}
    outs:
      - ${output_path}
    metrics:
      - ${metrics_path}:
          cache: true