dataset_kind: yanr
dataset_path: data/raw/yanr_10k.csv
processed_path: data/processed/yanr_10k.txt
coins_path: data/external/coins.json
leave_coins_uppercase: 1
remove_punctuation: 1
remove_non_alnum: 1
remove_stopwords: 1
lemmatize: 1
min_sentence_length: 2
min_word_length: 2
model_path: models/word2vec.bin.gz
metrics_path: models/metrics.json
vector_size: 100
alpha: 0.025
window: 5
min_count: 5
max_vocab_size: 1000000000
sample: 0.001
seed: 42
workers: 1
min_alpha: 0.0001
sg: 0
hs: 0
negative: 5
ns_exponent: 0.75
cbow_mean: 1
epochs: 5
batch_words: 10000
max_final_vocab: 1000000000
shrink_windows: 1